# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-starter',
                'doc_host': 'https://buildLittleWorlds.github.io',
                'git_url': 'https://github.com/buildLittleWorlds/nbdev-starter',
                'lib_path': 'nbdev_starter'},
  'syms': {'nbdev_starter.core': {'nbdev_starter.core.foo': ('core.html#foo', 'nbdev_starter/core.py')}}}
